from enum import Enum


class ErrorCode(str, Enum):
    INVALID_CASHBACK_VALUE = "INVALID_CASHBACK_VALUE"
    INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
    INVALID_MONTHLY_CAP = "INVALID_MONTHLY_CAP"
    MERCHANT_NOT_ACTIVE = "MERCHANT_NOT_ACTIVE"
    ACTIVE_OFFER_ALREADY_EXISTS = "ACTIVE_OFFER_ALREADY_EXISTS"
