"""add feature_flags table

Revision ID: 46afc1459aaf
Revises: ca7009b49525
Create Date: 2026-03-28 08:22:47.575843

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46afc1459aaf"
down_revision: Union[str, Sequence[str], None] = "ca7009b49525"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "scope_type",
            sa.String(),
            server_default=sa.text("'global'"),
            nullable=False,
        ),
        sa.Column("scope_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feature_flags_id"), "feature_flags", ["id"], unique=False)
    op.create_index(
        "ix_feature_flags_key_scope_lookup",
        "feature_flags",
        ["key", "scope_type", "scope_id"],
        unique=False,
    )
    op.create_index(
        "uq_feature_flags_key_scope",
        "feature_flags",
        ["key", "scope_type", sa.literal_column("coalesce(scope_id, '')")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_feature_flags_key_scope", table_name="feature_flags")
    op.drop_index("ix_feature_flags_key_scope_lookup", table_name="feature_flags")
    op.drop_index(op.f("ix_feature_flags_id"), table_name="feature_flags")
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
