"""add offers table

Revision ID: fba8773f9846
Revises: de09c6256aea
Create Date: 2026-03-02 16:46:45.942507

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fba8773f9846"
down_revision: Union[str, Sequence[str], None] = "de09c6256aea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.Column("fixed_amount", sa.Float(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("monthly_cap_per_user", sa.Float(), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_offers_id"), "offers", ["id"], unique=False)
    op.create_index(
        "ix_offers_merchant_active", "offers", ["merchant_id", "active"], unique=False
    )
    op.create_index("ix_offers_merchant_id", "offers", ["merchant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_offers_merchant_id", table_name="offers")
    op.drop_index("ix_offers_merchant_active", table_name="offers")
    op.drop_index(op.f("ix_offers_id"), table_name="offers")
    op.drop_table("offers")
    # ### end Alembic commands ###
