from enum import Enum


class ErrorCode(str, Enum):
    MERCHANT_NOT_ELIGIBLE = "MERCHANT_NOT_ELIGIBLE"
    USER_NOT_ELIGIBLE = "USER_NOT_ELIGIBLE"
    DUPLICATE_PURCHASE = "DUPLICATE_PURCHASE"
    OFFER_NOT_AVAILABLE = "OFFER_NOT_AVAILABLE"
    UNSUPPORTED_CURRENCY = "UNSUPPORTED_CURRENCY"
    INVALID_PURCHASE_STATUS = "INVALID_PURCHASE_STATUS"
    PURCHASE_ALREADY_REVERSED = "PURCHASE_ALREADY_REVERSED"
    PURCHASE_NOT_PENDING = "PURCHASE_NOT_PENDING"
